networks:
  default:
    driver: bridge
    name: roboshop
    external: true # If you want to use an existing network, set this to true and provide the name of the network. otherwise, set it to false and Docker will create a new network for you.
services:
  mongodb:
    image: viswanadhammanchem/mongodb:v1
    container_name: mongodb

  redis:
    image: viswanadhammanchem/redis:v1
    container_name: redis

  mysql:
    image: viswanadhammanchem/mysql
    container_name: mysql

  rabbitmq:
    image: viswanadhammanchem/rabbitmq:v1
    container_name: rabbitmq

  catalogue:
    image: viswanadhammanchem/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb

  user:
    image: viswanadhammanchem/user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    image: viswanadhammanchem/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  
  shipping:
    image: viswanadhammanchem/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart
  
  payment:
    image: viswanadhammanchem/payment:v1
    container_name: payment
    depends_on:
    - rabbitmq
  frontend:
    image: viswanadhammanchem/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment